---
title: "Statistics and Econometrics for Humanitarian Data Analysis"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## UNHCR Population Statistics - Formulary

Formula to calculate __population flows__: 

$# of refugees at the end of the period - # of refugees at the beginning of the period$

Some standard UNHCR __pending asylum application__ formulas:

$Total decided = # of cases recognised+# of cases rejected+# of cases Otherwise Closed$

$Pending Begin =  # of cases pending at the end of the previous period$

$Pending End = # of cases from Pending Begin + # of new applications - # of cases decided$

Pending cases are open cases where a decision regarding refugee status determination needs to be made.
The figure otherwise closed includes any case that is closed when a substantive decision isn't made (e.g. asylum seeker did not show up for the interview).

Formulas to measure __recognition rates__:

$Recognition rate for a specific period=\frac{Successful applications for refugee status}{All the substantive decisions within that period}×100$

Recognition rate calculations include cases of individual recognition and exclude prima facie cases. They also exclude any cases that were closed without a decision being made.  

$Refugee recognition rate=\frac{# of recognised cases}{# of recognised + # of complementary + # of rejected cases}×100$

$Total recognition rate=\frac{# of recognised+# of complementary cases}{# of recognised + # of complementary + # of rejected cases}×100$

The complementary protection is a formal permission under national law, provided on humanitarian grounds to persons who are in need of international protection to reside in a country, and might not qualify for refugee status under conventional refugee criteria.
The last two formulas only include cases of individual recognition, not cases where recognition was granted on a group basis. They include both new processed cases and cases imported into the period as pending and on which a substantive decision has been made. They combine both Government and UNHCR data if necessary. Finally, they calculate separate rates for each individual instance level of the decision process.

Reference: ODM Module 4 - _Introduction to UNHCR Population Statistics_.
