---
title: "Introductory Econometrics"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This course is based on the [lecture slides](http://scholar.harvard.edu/stock/publications/introduction-econometrics) which summarize the widely used book _Introduction to Econometrics_ by James Stock and Mark W. Watson. 
Each section of the previous course _Probability and Statistics_ except for _Statistics: Bayesian Inference_, is a prerequisite for this course.

### Ch. 1,2,3 - Review of Basic Probability and Statistics
__Key concepts__: difference-in-means test, population, random variable, probability distribution, moments of a population distribution, correlation coefficient, conditional distribution, conditional mean, randomly drawn distribution, estimation, sampling distribution, moments of a sampling distribution, law of large numbers (LLN), central limit theorem (CLT), hypothesis testing, p-value, significance level, student-t distribution, confidence interval.

### Ch. 4 - Introduction to Linear Regression
__Key concepts__: population linear regression model, least squares assumptions, sampling distribution of the regression parameters, ordinary least squares (OLS) estimation, hypothesis testing, confidence intervals, regression with binary independent variable, measure of fit $R^2$, standard error of the regression (SER), root mean squared error (RMSE), heteroskedasticity, homoskedasticity, formula for the standard errors of the parameters' estimators, heteroskedasticity-robust standard errors. 

### Ch. 5 - Multiple Regression
__Key concepts__: omitted variable bias, population multiple regression model, OLS estimator in multiple regression, least squares assumptions for multiple regression, perfect multicollinearity, sampling distribution of the OLS estimator, hypothesis test and confidence intervals for a single coefficient in multiple regression, tests of joint hypotheses, F-statistic, F distribution, $\chi^2$ distribution, testing single restrictions on multiple coefficients, confidence sets for multiple coefficients, $R^2$, standard error of the regression and $\bar{R}^2$ (adjusted $R^2$) for multiple regression.

### Ch. 6 - Nonlinear Regression Function - Nonlinearity in the Independent Variables
__Key concepts__: assumptions of the nonlinear population regression function, nonlinear functions of a single independent variable, polynomials in the dependent variable, logarithmic function, linear-log, log-linear and log-log population regression functions, interactions between independent variables (two binary variables, continuous and binary variables, two continuous variables).

### Ch. 7 - Assessing Studies Based on Multiple Regression
__Key concepts__: internal and external validity, threats to internal validity of multiple regression analysis: omitted variable bias, wrong functional form, errors-in-variables bias, sample selection bias, simultaneous causality bias.

### Ch. 8 - Regression with Panel Data 
__Key concepts__: panel data notation, panel data with two time periods, fixed effects (FE) regression (more than two time periods), FE estimation methods ($n-1$ binary regressors ols regression, entity-demeaned OLS regression, changes specification), regression with time FE, time FE estimation methods ($T-1$ binary regressors OLS regression, year-demeaned OLS regression), state and time FE estimation methods ($n-1$ and $T-1$ binary regressors OLS regression, state- and year-demeaned OLS regression), fixed FE regression assumptions.

### Ch. 9 - Regression with a Binary Dependent Variable
__Key concepts__: linear probability model (LPM), probit and logit regression, probit estimation by nonlinear least squares, probit and logit estimation by maximum likelihood, measures of fit (fraction correctly predicted, psuedo $R^2$), distribution of the maximum likelihood estimation.

### Ch. 10 - Instrumental Variables (IV) Regression
The authors present instrumental variables regression as a general method for handling correlation between the error term and a regressor, which can arise for many reasons, including omitted variables and simultaneous causality. The two assumptions for a valid instrument - exogeneity and relevance - are given equal billing. They explain where instruments come from and present tests of overidentifying restrictions as well as diagnostics for weak instruments. Furthermore, they explain what to do if these diagnostics suggest problems.

### Ch. 11 - Experiments and Quasi-Experiments
An increasing number of econometric studies analyze either randomized controlled experiments or quasi-experiments, also known as natural experiments. The authors address these topics, often collectively referred to as program evaluation in this Chapter. They present this research strategy as an alternative approach to the problems of omitted variables, simultaneous causality, and selection, and they assess both the strength and the weaknesses of studies using experimental or quasi-experimental data.

### Ch. 12 - Introduction to Time Series Regression and Forecasting 
This Chapter considers univariate and multivariate forecasts using time series regression, not large simultaneous equation structural models. The authors focus on simple and reliable tools, such as autoregressions and model selection via an information criterion, that work well in practice. This chapter also features a practically oriented treatment of stochastic trends (unit roots), and pseudo out-of-sample forecasting, all in the context of developing stable and reliable time series forecasting models.

### Ch. 13 - Estimation of Dynamic Casual Effects 
This Chapter pays careful attention to when different estimation methods, including generalized least squares, will or will not lead to valid causal inferences, and when it is advisable to estimate dynamic regressions using OLS with heteroskedasticity- and autocorrelation-consistent standard errors.


For online courses on introductory econometrics, watch/attend also:

* [Econometrics: Methods and Applications](https://www.coursera.org/learn/erasmus-econometrics) on Coursera
* [Introductory Econometrics for Finance](http://www.cambridge.org/us/academic/textbooks/introductory-econometrics/videos) by Cambridge University Press
* [Econometrics](https://www.youtube.com/view_play_list?p=783CDD8EF10BDDB9) by Mark Thoma

Reference: Stock J, Watson MW. _Introduction to Econometrics_. New York: Prentice Hall; 2003.
