---
title: "Probability and Statistics"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This course is mainly based on the lecture notes and slides, attached below, of the MIT open course [_Introduction to Probability and Statistics_](https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/) by Jeremy Orloff and Jonathan Bloom. Nevertheless, suggestions on other interactive online courses are included to enrich the knowledge of these two topics.

#### Goals of the course:
*	Learn the language and core concepts of probability theory.
*	Understand basic principles of statistical inference (both Bayesian and frequentist).
*	Build a starter statistical toolbox with appreciation for both the utility and limitations of these techniques.
*	Use software and simulation to do statistics (R).
*	Become an informed consumer of statistical information.
*	Prepare for further coursework or on-the-job study.

## Probability

First, a brief introduction to Probability: [What happens if you guess?](https://ed.ted.com/lessons/leigh-nataro-what-happens-if-you-guess)

Once this course will be completed, you will be able to:

*	use basic counting techniques (multiplication rule, combinations, permutations) to compute probability and odds;
*	use R to run basic simulations of probabilistic scenarios;
*	compute conditional probabilities directly and using Bayes theorem. And check for independence of events;
*	set up and work with discrete random variables. In particular, understand the Bernoulli, binomial, geometric and Poisson distributions;
*	know what expectation and variance mean and compute them;
*	understand the law of large numbers and the central limit theorem;
*	compute the covariance and correlation between jointly distributed variables.

[Introduction](/class1-intro.pdf)
Counting and Sets - Slides
Probability: Terminology and Examples - Slides
Conditional Probability, Independence and Bayes' Theorem - Slides
Discrete Random Variables
Discrete Random Variables: Expected Value - Slides
Variance of Discrete Random Variables
Continuous random Variables - Slides
Gallery of Continuous Random Variables
Manipulating Continuous Random Variables
Expectation, Variance and Standard Deviation of Continuous Random Variables
Central Limit Theorem and the Law of Large Numbers (R tutorial) - Slides (R tutorial) 
Joint Distributions, Independence
Covariance and Correlation - Slides (R tutorial)
Normal Table
Review Problems - Solutions - Review Slides


For online courses on Probability, watch/attend also: 

*	[Introduction to Probability and Data]( https://www.coursera.org/learn/probability-intro) (which includes the use of R/RStudio) on Coursera
*	[Introduction to Probability](https://www.edx.org/course/introduction-probability-science-mitx-6-041x-1) (which also covers Bayesian Statistics) on EdX
*	[Introduction to Statistics: Probability](https://www.edx.org/course/introduction-statistics-probability-uc-berkeleyx-stat2-2x) on EdX

## Statistics
Once this course will be completed, you will be able to:

*	create and interpret scatter plots and histograms;
*	understand the difference between probability and likelihood functions and to find the maximum likelihood estimate for a model parameter.
Introduction to Statistics
Maximum Likelihood Estimates - Slides

### Statistics: Bayesian Inference
Once this course will be completed, you will be able to:

*	do Bayesian updating with discrete priors to compute posterior distributions and posterior odds;
*	do Bayesian updating with continuous priors;
*	construct estimates and predictions using the posterior distribution;
*	find credible intervals for parameter estimates.

Bayesian Updating with Discrete Priors - Slides
Bayesian Updating: Probabilistic Prediction
Bayesian Updating: Odds - Slides
Bayesian updating with Continuous Priors
Notational Conventions - Slides (R tutorial)
Beta Distributions
Continuous Data with Continuous Priors - Slides
Conjugate Priors: Beta and Normal - Slides (R tutorial)
Choosing Priors
Probability Intervals - Slides (R tutorial)

### Statistics: Frequentist Inference
Once this course will be completed, you will be able to:

*	use null hypothesis significance testing (NHST) to test the significance of the results, understand and compute the p-value for these tests;
*	use specific significance tests including z-test, t-test (one and two sample), chi-squared test.

The Frequentist School of Statistics
Null Hypothesis Significance testing I - Slides (R tutorial)
Null Hypothesis Significance Testing II (R tutorial) - Slides (R tutorial)
Null Hypothesis Significance Testing III - Slides
Comparison of Frequentist and Bayesian Inference - Slides (R tutorial)
Summary

### Statistics: Confidence Intervals - Regressions
Once this course will be completed, you will be able to:

*	find confidence intervals for parameter estimates;
*	use bootstrapping estimate confidence intervals;
*	compute and interpret simple linear regression between two variables;
*	set up a least squares fit of data to a model.
Confidence Intervals Based on Normal Data - Slides (R tutorial)
Confidence Intervals: Three Views
Confidence Intervals for the Mean of Non-normal Data - Slides (R tutorial)
Bootstrap Confidence Interval (R tutorial) - Slides (R empirical bootstrap, R parametric bootstrap, R tutorial)
Linear Regression (R tutorial) - Slides (R tutorial)


Final Review Problems - Solutions


For online courses on Statistics, watch/attend also:

*	[Basic Statistics on Coursera](https://www.coursera.org/learn/basic-statistics)
*	[Bayesian Statistics - Inferential Statistics on Coursera](https://www.coursera.org/learn/bayesian)
*	[Descriptive Statistics - Inference on EdX](https://www.edx.org/course/introduction-statistics-descriptive-uc-berkeleyx-stat2-1x)
*	[Methods and Statistics in Social Sciences on Coursera](https://www.coursera.org/specializations/social-science)
*	[Data Analysis for Social Scientists on EdX](https://www.edx.org/course/data-analysis-social-scientists-mitx-14-310x)



Reference: Jeremy Orloff, and Jonathan Bloom. 18.05 _Introduction to Probability and Statistics_. Spring 2014. Massachusetts Institute of Technology: MIT OpenCourseWare, https://ocw.mit.edu. License: Creative Commons BY-NC-SA.